# Font

font_family      IBM Plex Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.0

# Cursor

cursor_shape block
cursor_blink_interval 0.5

shell_integration no-cursor

# Window

window_padding_width 4
background_opacity 1.00
dynamic_background_opacity yes
confirm_os_window_close 0

# Tabs

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted

# Keymaps

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# ----------------
# Theme
# ----------------

# ANSI 1987
include current-theme.conf
